agenda/urls.py
from django.conf.urls import url
from . import views

app_name = 'agenda'

urlpatterns = [
    url(r'^$', views.form, name='form'),
    url(r'^submit/$', views.submit, name='submit'),
    #url(r'^ver/(?P<slug>[\w-]+)/$', views.detail, name='detail'),
]

atividade/urls.py
from django.conf.urls import url
from . import views

app_name = 'atividade'

urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^ver/(?P<slug>[\w-]+)/$', views.detail, name='detail'),
]

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

teora/urls.py
from django.conf.urls import (
    include,
    url,
    )

from django.contrib import admin

from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    #teora urls
    url(r'^', include('home.urls')),
    url(r'^atividade/', include('atividade.urls')),
    url(r'^agenda/', include('agenda.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agenda/models.py
from django.db import models

from atividade.models import AtividadeInfo

class Agendamento(models.Model):
    atividade_info = models.ForeignKey(AtividadeInfo, blank=True, null=True)
    nome = models.CharField(max_length=40)
    telefone = models.CharField(max_length=40)
    email = models.CharField(max_length=40, blank=True, null=True)

    def __str__(self):
        return '%s - %s' % (self.nome, self.atividade_info.atividade.nome)

atividade/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
import os

class Atividade(models.Model):
    nome = models.CharField(max_length=40)
    slug = models.SlugField(unique=True, blank=True, null=True)
    foto = models.FileField(upload_to='home/static/uploads/')
    descricao = models.TextField()

    def __str__(self):
        return self.nome

    def get_foto_url(self):
        foto_url = os.path.basename(self.foto.name)
        foto_url = '/assets/uploads/' + foto_url
        return foto_url


class AtividadeInfo(models.Model):
    atividade = models.ForeignKey(Atividade)
    horario = models.CharField(max_length=40, blank=True)
    valor = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    endereco = models.CharField(max_length=100)

    def __str__(self):
        return '%s - %s - %s' % (self.atividade.nome, self.horario, self.endereco)

def create_slug(instance, new_slug=None):
    slug = slugify(instance.nome)
    if new_slug is not None:
        slug = new_slug
    qs = Atividade.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, sender=Atividade)

home/models.py
from django.db import models

# Create your models here.

agenda/forms.py
from django import forms

from .models import (
    Agendamento,
    )

class AgendamentoForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(AgendamentoForm, self).__init__(*args, **kwargs)
        self.fields['nome'].widget.attrs['placeholder'] = 'Nome'
        self.fields['nome'].widget.attrs['class'] = 'form-control'
        self.fields['telefone'].widget.attrs['placeholder'] = 'Telefone'
        self.fields['telefone'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['atividade_info'].label = 'Atividade'
        self.fields['atividade_info'].widget.attrs['class'] = 'form-control'

    class Meta:
        model = Agendamento
        fields = ['nome', 'telefone', 'email', 'atividade_info']

agenda/views.py
from django.shortcuts import (
    get_object_or_404,
    render
    )

from .forms import (
    AgendamentoForm,
    )

from .models import (
    Agendamento,
    )

from atividade.models import (
    Atividade,
    AtividadeInfo
    )

def form(request):
    atividade_info_id = request.GET.get('atividade_info_id')
    atividade_info = None
    if atividade_info_id is not None:
        atividade_info = AtividadeInfo.objects.filter(id=atividade_info_id).first()
    form = AgendamentoForm(request.POST or None, initial={'atividade_info': atividade_info})
    context = {
        'atividade_info': atividade_info,
        'form': form,
    }
    return render(request, 'agenda/form.html', context)

def submit(request):
    form = AgendamentoForm(request.POST or None)
    context = {
        'form': form,
    }
    if request.method == 'POST' and form.is_valid():
        agendamento = form.save(commit=False)
        agendamento.atividade_info = form.cleaned_data['atividade_info']
        agendamento.nome = form.cleaned_data['nome']
        agendamento.telefone = form.cleaned_data['telefone']
        agendamento.email = form.cleaned_data['email']
        agendamento.save()
        context.update({
            'agendamento': agendamento,
        })
        return render(request, 'agenda/obrigado.html', context)
    return render(request, 'agenda/form.html', context)

atividade/views.py
from django.shortcuts import (
    get_object_or_404,
    render
    )

from django.db.models import Q

from .models import (
    Atividade,
    AtividadeInfo
    )

def list(request):
    atividade = atividade = Atividade.objects.all().order_by('nome')
    search = request.GET.get('search')
    if search is not None:
        atividade = atividade.filter(Q(nome__contains=search))
    count = atividade.count()
    context = {
        'atividade': atividade,
        'count': count,
        'search': search,
    }
    return render(request, 'atividade/list.html', context)

def detail(request, slug):
    atividade = get_object_or_404(Atividade, slug=slug)
    atividade_info = AtividadeInfo.objects.filter(atividade__slug=slug).order_by('horario')
    context = {
        'atividade': atividade,
        'atividade_info': atividade_info,
    }
    return render(request, 'atividade/detail.html', context)

home/views.py
from django.shortcuts import render

from atividade.models import (
    Atividade,
    AtividadeInfo
    )

# Create your views here.
def index(request):
    atividade = Atividade.objects.all().order_by('nome')
    context = {
        'atividade': atividade,
    }
    return render(request, 'home/home.html', context)

agenda/templates/agenda/form.html
{% extends 'home/base.html' %}

{% block body %}
    <div class="section section_aboutus">
    	<div id="map" style="height: 400px;width: 100%;"></div>
        <div class="container">
            <h2 class="section-title">Mande sua mensagem</h2>
            <div class="row">
                <div class="col-md-6">
                    <p>
                        Contate-nos. Assim que possível, entraremos retornaremos.<br /><br />
                    </p>
                    	<div id="divForm">
                        <form action="{% url 'agenda:submit' %}" method="post" role="form">
                          {% csrf_token %}
                            <div class="form-group">
                              {% for field in form %}
                                <label for="{{field.id_for_label}}" class="control-label" style="margin-top: 8px;">{{field.label_tag}}</label>
                                {{field}}
                              {% endfor %}
                            </div>
                            <div class="submit" style="text-align: center;">
                                <input type="submit" id="submitButton" name="submitButton" class="btn btn-youseg" value="Envie sua mensagem" />
                                <img id="imgLoading" style="display:none" height="60px" src="../assets/img/loading.gif" />
                            </div>
                        </form>
                        </div>
                        <p id="msgEnviada" style="display: none">Mensagem enviada com sucesso! Aguarde que entraremos em contato!<br /><br /></p>
                        <p id="msgErro" style="display: none">Erro ao enviar a mensagem! Tente novamente!<br /><br /></p>
                </div>
                <div class="col-md-4 col-md-offset-2">
                    <div class="contact-info">
                        <h5><i class="fa fa-map-marker text-muted"></i> Endereço</h5>
                        <p class="text-muted"> Avenida Maurílio Biagi, 800, sala 1104 - Ribeirânia<br />
                            CEP: 14096-075<br />
                            Ribeirão Preto - SP
                        </p><br />
                        <h5><i class="fa fa-phone text-muted"></i> Telefone</h5>
                        <p class="text-muted"> Teora<br />
                            (16) 2102-1234<br />
                            Segunda à sexta-feira<br />
                            8:00h - 18:00h
                        </p><br />
                    </div>
                </div>
            </div>
        </div>
    </div><!-- section -->
    <div class="space-50"></div>
    {% endblock %}
{% block js %}
<script type="text/javascript">
	function initMap() {
      var myLatlng = new google.maps.LatLng(-21.201500, -47.795528);
      var mapOptions = {
          zoom: 15,
          center: myLatlng,
          scrollwheel: false, //we disable de scroll over the map, it is a really annoing when you scroll through page
      };

      var map = new google.maps.Map(document.getElementById("map"), mapOptions);

      var marker = new google.maps.Marker({
          position: myLatlng,
          title: "youSeg"
      });

      marker.setMap(map);
	}
</script>
<script src="https://maps.googleapis.com/maps/api/js?callback=initMap"></script>
{% endblock %}

atividade/templates/atividade/detail.html
{% extends 'home/base.html' %}

{% block body %}
	<div class="section section_aboutus">
	    <div class="container" id="blog-cards">
	        <div class="col-md-12" style="margin-top: 30px;">
	            <div class="card card-name">
   	                <div class="row">
                        <div class="col-md-12" style="vertical-align: middle;">
                            <h5 style="text-align: center; text-transform: uppercase; margin-bottom: 10px !important;"><strong><th>{{atividade.nome}}</th></strong></h5>
                         </div>
	                </div>
	            </div>
	            <div class="card card-horizontal">
	                <div class="row">
	                    <div class="col-md-4" align="center">
	                        <div class="image_services">
	                            <img src="{{atividade.get_foto_url}}" />
	                        </div>
	                    </div>
	                    <div class="col-md-8">
	                        <div style="margin: 20px 0 0 0;">
	                            <div style="margin-top: 5px;">
	                                <div class="col-md-12">
		                            	<p align="justify"><th>{{atividade.descricao}}</th></p>
	                                </div>
	                            </div>

	                        </div>
	                    </div>
	                </div>
	            </div>
	            <!-- end card -->
            </div>
			<div class="col-md-12" id="divContentArea">
			    <div class="container_source">
			         <div class="info prestador-home-content active" id="menuContent">
				        <div id="divCategorias">
			            <div class="" id="nav-filter-53HL">
			                <div class="headline ">
			                    <h3>Horários e Valores</h3>
			                </div>
                      <div class="inline-popup">
                        {% for info in atividade_info %}
                          <div class="result-text clearfix">
                              <div class="col-md-8" style="text-align: left;">
                                  <h4 style="margin-top: 5px"><th>{{info.horario}}</th></h4>
                                  <p style="margin-bottom: 15px"><th>{{info.endereco}}</th></p>
                              </div>
                              <div class="col-md-2">
                                {% if info.valor > 0 %}
                                  <p style="font-size: 13px;">A partir de</p>
                                  <p><strong>R$ <th>{{info.valor}}</th></strong></p>
                                {% else %}
                                  <p style="margin-top: 20px;"><strong>Gratuito</strong></p>
                                {% endif %}
                              </div>
                              <div class="col-md-2" style="margin-top: -15px;">
                                    <div class="top_bay">
                                        <a class="box_text" href="{% url 'agenda:form' %}?atividade_info_id={{info.id}}">
                                            <h2>Inscreva-se!</h2>
                                        </a>
                                    </div>
                              </div>
                          </div>
                        {% endfor %}
                      </div>
			            </div>
			            <!-- /.results-section -->
			        </div>
			    </div>
			</div>
	    </div>
    </div>
  </div>

{% endblock %}

atividade/templates/atividade/list.html
{% extends 'home/base.html' %}

{% block body %}

		<div class="section section_aboutus">

			<div class="menus" style="position:relative">
					<div id="filterMobile" class="filter">
						<div style="position:relative; text-align: center;">
							<ul>
								<li class="col-md-12" style="text-align: left !important"><label for="divBuscas" style="color:white; margin-left: 0;">Busca:</label>
									<div id="divBuscas" class="searchBarFilter" style="margin-top: -10px;">
										<div class="search-bar">
											<form method="get" action="{% url 'atividade:list' %}">
											<div class="field-wrap">
												<input type="text" name="search" id="searchFilterField" class="field" placeholder="Busque pela atividade que você quer conhecer..." />
											</div>
											<input type="submit" class="btn-search" />
											</form>
										</div>
									</div>
								</li>
							</ul>
						</div>
					</div>
			</div>

        <div class="container" id="blog-cards">
            <div style="margin-bottom: 20px;">
                <h3 style="margin-left: 15px;margin-top: 15px;">Atividades em Ribeirão Preto</h3>
                <hr />
                <div id="divPrestadores">
									{% if count == 0 %}
									<p>Não foram encontradas atividades com as palavras: {{search}}.</p>
									{% endif %}
                {% for atv in atividade %}
        				<div class="col-md-4">
        				    <div class="card" style="padding-bottom: 1%;">
        				        <div class="image_services">
        				            <img src="{{atv.get_foto_url}}" />
        				            <div class="filter">
        				            	<a class="btn btn-neutral btn-simple" href="{% url 'atividade:detail' atv.slug %}"><i class="fa fa-bookmark-o"></i> Ver Detalhes</a>
        				            </div>
        				        </div>
        				        <div class="content" style="position: relative; min-height: 110px; text-align:center;">
        			                <div class="col-md-12" style="padding-left: 0px; padding-right: 0px;">
        			                    <h4 class="title_prof"><strong>{{atv.nome}}</strong></h4>
        			                </div>
          				            <div class="footer col-md-12" style="margin-top: 5px; bottom: 10px; margin-right: 15px;">
          				                <div style="margin-top: 5px; width: 100%;">
          				                	<a class="btn btn-simple" style="border: 1px solid;border-color: #FD9941;width: 100%;height: 50px;border-radios: 10px;background-color: #FD9941;color: #FFFFFF;line-height: 30px;" href="{% url 'atividade:detail' atv.slug %}">
          				                    	<i class="fa fa-bookmark-o"></i> Ver Detalhes</a>
          				                </div>
          				            </div>
        				        </div>
          			    </div> <!-- end card -->
                </div>
    	          {% endfor %}
				</div>

		</div>
		</div>
		</div>
{% endblock %}

home/templates/home/base-home.html
{% load static %}
<!DOCTYPE HTML>

<html>

<head>
    <title>Teora</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
    <meta name="viewport" content="width=device-width" />
    <meta name="description" content="Serviços rápidos para facilitar seu dia!" />

    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet" media="screen" />

    <link rel="stylesheet" media="screen" href="{% static '/css/gsdk.css' %}" />

    <link rel="stylesheet" media="screen" href="{% static '/css/demo.css' %}" />

    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Grand+Hotel|Open+Sans:400,300" rel="stylesheet" type="text/css" />

    <link rel="stylesheet" media="screen" href="{% static '/css/pe-icon-7-stroke.css' %}" />

    <script src="{% static '/js/jquery.min.js' %}"></script>

	<script src="{% static '/js/bootstrap.js' %}"></script>

  <link rel="stylesheet" media="screen" href="{% static 'css/examples.css' %}" />

  <link rel="stylesheet" media="screen" href="{% static 'css/menu.css' %}" />

  <link rel="stylesheet" media="screen" href="{% static 'css/main.css' %}" />

</head>
<body>
<style>


.test:not (.nohover ):hover {
  border: 1px solid red;
}

.btnPrestador {
  background: #EDA901;
    display: block;
    border-radius: 8px;
    line-height: 47px;
    text-align: center;
    font-size: 18px;
    color: #fff;
    font-weight: 600;
    cursor: pointer;
}

.notUnderline {
  text-decoration: none !important;
}

.prestadorTitle {
  color: blue !important;
  font-size: 16px !important;
  padding-top: 0 !important;
}

.class:hover {
    background-color: #edb831 !important;
}

</style>
<nav class="navbar navbar-ct-silver navbar-fixed-top" role="navigation" style="position:absolute; margin-bottom: 0px;">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button id="menu-toggle" type="button" class="navbar-toggle">
                <span class="sr-only">Navegação</span>
                <span class="icon-bar bar1"></span>
                <span class="icon-bar bar2"></span>
                <span class="icon-bar bar3"></span>
            </button>
            <a class="navbar-brand" href="/">
                <img src="{% static '/img/logoTeora.png' %}" alt="" width="156px" style="margin-top: -13px;" />
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse">

            <ul class="nav navbar-nav navbar-right">
                
                <li><a href="{% url 'atividade:list' %}">Atividades</a></li>
                <li><a href="{% url 'agenda:form' %}">Contato</a></li>
            </ul>

        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->

</nav>



<div class="wrapper">
  {% block body %}
  {% endblock %}

    <div class="section section-gray" id="footers">

        <footer class="footer footer-big footer-transparent" style="background-image: url('{% static '/img/footer02.jpg' %}')">

            <!-- .footer-black is another class for the footer, for the transparent version, we recommend you to change the url of the image with your favourite image.          -->

            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-md-offset-1">

                        </nav>
                    </div>
                    <div class="col-md-3 col-md-offset-1">

                        <nav>

                        </nav>
                    </div>
                    <div class="col-md-3 col-md-offset-1">

                        </nav>
                    </div>
                </div>
                <hr />
                <div class="social-area text-center">
                    <h5>Siga-nos nos links abaixo </h5>
                    <a href="https://www.facebook.com/voceseg/" target="_blank" class="btn btn-social btn-round">
                        <i class="fa fa-facebook"></i>
                    </a>
                    <a href="https://www.instagram.com/voceseguro/" target="_blank" class="btn btn-social btn-round">
                        <i class="fa fa-instagram"></i>
                    </a>
                    <a href="https://plus.google.com/u/0/107761337422012203268/about" target="_blank" class="btn btn-social btn-round">
                        <i class="fa fa-google-plus"></i>
                    </a>
                    <a href="https://www.linkedin.com/company/10323729" target="_blank" class="btn btn-social btn-round">
                        <i class="fa fa-linkedin"></i>
                    </a>
                    <a href="https://www.youtube.com/channel/UCmqn6C-8WyHuBuW82fH9kew" target="_blank" class="btn btn-social btn-round">
                        <i class="fa fa-youtube"></i>
                    </a>
                </div>

                <div class="copyright">
                    © Copyright 2017 - Todos os direitos reservados para Teora
                </div>
            </div>
        </footer>
    </div>

</div>
<!-- end wrapper -->

<!-- </div> -->

</body>

<!--  jQuery and Bootstrap core files    -->
<script type="text/javascript" src="{% static '/js/jquery-ui.custom.min.js' %}"></script>

<!--  Plugins -->
<script src="{% static '/js/gsdk-checkbox.js' %}"></script>
<script src="{% static '/js/gsdk-morphing.js' %}"></script>
<script src="{% static '/js/gsdk-radio.js' %}"></script>
<script src="{% static '/js/gsdk-bootstrapswitch.js' %}"></script>
<script src="{% static '/js/bootstrap-select.js' %}"></script>
<script src="{% static '/js/bootstrap-datepicker.js' %}"></script>
<script src="{% static '/js/chartist.min.js' %}"></script>
<script src="{% static '/js/jquery.tagsinput.js' %}"></script>
<script src="{% static '/js/login-register.js' %}"></script>
<script src="{% static '/js/jquery.mask.min.js' %}"></script>
<script src="{% static '/js/search.js' %}"></script>

<!--  Get Shit Done Kit PRO Core javascript 	 -->
<script src="{% static '/js/main.js' %}"></script>

<!--  Get Shit Done Kit PRO methods used for demo purpose      -->
<script src="{% static '/js/custom.js' %}"></script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-80192282-1', 'auto');
  ga('send', 'pageview');

</script>

	<script type="text/javascript">
		function selectedAtividade() {
			var selectBox = document.getElementById("selectAtividade");
			var selectedValue = selectBox.options[selectBox.selectedIndex].value;
			if (selectedValue != 0) {
				document.location.href = "/atividade/ver/" + selectedValue + "/";
			}
		}
	</script>

  {% block js %}
  {% endblock %}
</html>

home/templates/home/base.html
{% load static %}
<!DOCTYPE HTML>

<html>

<head>
    <title>Teora</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
    <meta name="viewport" content="width=device-width" />
    <meta name="description" content="Serviços rápidos para facilitar seu dia!" />

    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet" media="screen" />

    <link rel="stylesheet" media="screen" href="{% static '/css/gsdk.css' %}" />

    <link rel="stylesheet" media="screen" href="{% static '/css/demo.css' %}" />

    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Grand+Hotel|Open+Sans:400,300" rel="stylesheet" type="text/css" />

    <link rel="stylesheet" media="screen" href="{% static '/css/pe-icon-7-stroke.css' %}" />

    <script src="{% static '/js/jquery.min.js' %}"></script>

	<script src="{% static '/js/bootstrap.js' %}"></script>

  <link rel="stylesheet" media="screen" href="{% static 'css/examples.css' %}" />

  <link rel="stylesheet" media="screen" href="{% static 'css/menu.css' %}" />

  <link rel="stylesheet" media="screen" href="{% static 'css/main.css' %}" />

</head>
<body>
<style>


.test:not (.nohover ):hover {
  border: 1px solid red;
}

.btnPrestador {
  background: #EDA901;
    display: block;
    border-radius: 8px;
    line-height: 47px;
    text-align: center;
    font-size: 18px;
    color: #fff;
    font-weight: 600;
    cursor: pointer;
}

.notUnderline {
  text-decoration: none !important;
}

.prestadorTitle {
  color: blue !important;
  font-size: 16px !important;
  padding-top: 0 !important;
}

.class:hover {
    background-color: #edb831 !important;
}

</style>
<nav class="navbar navbar-ct-silver navbar-fixed-top" role="navigation" style="position:relative; margin-bottom: 0px;">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button id="menu-toggle" type="button" class="navbar-toggle">
                <span class="sr-only">Navegação</span>
                <span class="icon-bar bar1"></span>
                <span class="icon-bar bar2"></span>
                <span class="icon-bar bar3"></span>
            </button>
            <a class="navbar-brand" href="/">
                <img src="{% static 'img/logoTeora.png' %}" alt="" width="156px" style="margin-top: -13px;" />
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse">

            <ul class="nav navbar-nav navbar-right">


                        
                    </a>

                </li>
                <li><a href="{% url 'atividade:list' %}">Atividades</a></li>
                <li><a href="{% url 'agenda:form' %}">Contato</a></li>
            </ul>

        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->

</nav>


<div class="wrapper">
  {% block body %}
  {% endblock %}

    <div class="section section-gray" id="footers">

        <footer class="footer footer-big footer-transparent" style="background-image: url('{% static '/img/footer02.jpg' %}')">

            <!-- .footer-black is another class for the footer, for the transparent version, we recommend you to change the url of the image with your favourite image.          -->

            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-md-offset-1">

                        </nav>
                    </div>
                    <div class="col-md-3 col-md-offset-1">

                        <nav>

                        </nav>
                    </div>
                    <div class="col-md-3 col-md-offset-1">

                        <nav class="numbers">

                        </nav>
                    </div>
                </div>
                <hr />
                <div class="social-area text-center">
                    <h5>Siga-nos nos links abaixo </h5>
                    <a href="https://www.facebook.com/voceseg/" target="_blank" class="btn btn-social btn-round">
                        <i class="fa fa-facebook"></i>
                    </a>
                    <a href="https://www.instagram.com/voceseguro/" target="_blank" class="btn btn-social btn-round">
                        <i class="fa fa-instagram"></i>
                    </a>
                    <a href="https://plus.google.com/u/0/107761337422012203268/about" target="_blank" class="btn btn-social btn-round">
                        <i class="fa fa-google-plus"></i>
                    </a>
                    <a href="https://www.linkedin.com/company/10323729" target="_blank" class="btn btn-social btn-round">
                        <i class="fa fa-linkedin"></i>
                    </a>
                    <a href="https://www.youtube.com/channel/UCmqn6C-8WyHuBuW82fH9kew" target="_blank" class="btn btn-social btn-round">
                        <i class="fa fa-youtube"></i>
                    </a>
                </div>

                <div class="copyright">
                    © Copyright 2017 - Todos os direitos reservados para Teora
                </div>
            </div>
        </footer>
    </div>

</div>
<!-- end wrapper -->

<!-- </div> -->

</body>

<!--  jQuery and Bootstrap core files    -->
<script type="text/javascript" src="{% static '/js/jquery-ui.custom.min.js' %}"></script>

<!--  Plugins -->
<script src="{% static '/js/gsdk-checkbox.js' %}"></script>
<script src="{% static '/js/gsdk-morphing.js' %}"></script>
<script src="{% static '/js/gsdk-radio.js' %}"></script>
<script src="{% static '/js/gsdk-bootstrapswitch.js' %}"></script>
<script src="{% static '/js/bootstrap-select.js' %}"></script>
<script src="{% static '/js/bootstrap-datepicker.js' %}"></script>
<script src="{% static '/js/chartist.min.js' %}"></script>
<script src="{% static '/js/jquery.tagsinput.js' %}"></script>
<script src="{% static '/js/login-register.js' %}"></script>
<script src="{% static '/js/jquery.mask.min.js' %}"></script>
<script src="{% static '/js/search.js' %}"></script>

<!--  Get Shit Done Kit PRO Core javascript 	 -->
<script src="{% static '/js/main.js' %}"></script>

<!--  Get Shit Done Kit PRO methods used for demo purpose      -->
<script src="{% static '/js/custom.js' %}"></script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-80192282-1', 'auto');
  ga('send', 'pageview');

</script>

	<script type="text/javascript">
		function selectedAtividade() {
			var selectBox = document.getElementById("selectAtividade");
			var selectedValue = selectBox.options[selectBox.selectedIndex].value;
			if (selectedValue != 0) {
				document.location.href = "/atividade/ver/" + selectedValue + "/";
			}
		}
	</script>

  {% block js %}
  {% endblock %}
</html>